---
title: "Untitled"
output: html_document
---
## Question 5

What is the relationship between the price margins of the
  Intrade market and the actual margin of victory? Using only the
  market data from the day before the election in 2008, regress
  Obama's actual margin of victory in each state on Obama's price
  margin from the Intrade markets. Similarly, in a separate analysis,
  regress Obama's actual margin of victory on the Obama's predicted
  margin from the latest polls within each state. Interpret the
  results of these regressions.
  
  
## Question 6


Do the 2008 predictions of polls and Intrade accurately predict
  each state's 2012 elections results?  Using the fitted regressions
  from the previous question, forecast Obama's actual margin of
  victory for the 2012 election in two ways.  First, use the 2012
  Intrade price margins from the day before the election as the
  predictor in each state.  Recall that the 2012 Intrade data do not
  contain market prices for all states. Ignore states without data.
  Second, use the 2012 poll predicted margins from the latest polls in
  each state as the predictor, found in `polls12.csv`.